### ISSUE TITLE
Possible errors by non-conventional characters

### ISSUE THREAD

**Issue by andromeda979** [KITPraktomatTeam/Praktomat#233]
Dear all, 

I want to suggest to implement the regular expression: 

**“^[a-zA-Z0-9_ . \-\?\!]*\.[cC]$”**  
since it is of statistical interest, taking into account the number of students that use non-conventional characters to upload its own solution (in the first year of University). Currently, Praktomat gives back an error, without compiling: As a possible side effect, the student that is used to other IDEs in which the same solution do not represent a error source, e.g. Visual studio, is discouraged to use Praktomat.
Here you can find a list of few possible error sources:

**Hello World.c**   _(The "space” between two words has been corrected after my first highlighting)_ 
**Helloworld!.c
Helloworld?.c
Hello-world!.c
My Solution-1!.c**

**Builder.py**
`_file_pattern	  = models.CharField(max_length = 1000, default = r"^[^[a-zA-Z0-9_ . \-\?\!]*\.[cC]$]*$", help_text = _('Regular expression describing all source files to be passed to the compiler.'))`

**CBuilder.py**
`self.fields["_file_pattern"].initial = r"^[a-zA-Z0-9_ . \-\?\!]*\.[cC]$"`

**Comment by mhecker** [comment]
Hello!

I am reluctant to change the default C file pattern, since 

1. the default `r"^[a-zA-Z0-9_]*\.[cC]$"` *is*, in my opinion, a reasonable default, given the hassle of properly escaping characters like "!", and properly dealing with whitespaces in interactive shells
2. AFAICT, changing the default (as you seem to be doing) when creating C Tasks in Praktomat *does* work as intended in Praktomat: Students can upload such files, and they are properly compiled.
