### ISSUE TITLE
python 3.8.3 delivers "preexec_fn not supported within subinterpreters" error

### ISSUE THREAD

**Issue by chris21k** [KITPraktomatTeam/Praktomat#312]
Under Ubuntu 20.04 development branch, with python 3.8.3, running a checker delivers 
"preexec_fn not supported within subinterpreters" (with setting DEBUG = True in local.py, see [RuntimeError at _tasks_1_solutionupload_test_.zip](https://github.com/KITPraktomatTeam/Praktomat/files/4682043/RuntimeError.at._tasks_1_solutionupload_test_.zip)). More precisely, I upload a test solution to task, and the Java builder/compile checker fails.
Praktomat is served by Apache via the wsgi-plugin. It helps to eliminate the preexec_fn=prepare_subprocess parameter from the subprocess.Popen command in untilities/safeexec.py around line 79. However, I am not sure, if this has some negative side effects. The reason might be, that this param causes problems in combination with wsgi, e.g., see https://bugs.python.org/issue37951 with newer python releases. Please have a look, this is a critical blocker.

Thanks,
Chris

**Comment by michaelfruth** [comment]
I also encountered this problem and as a workaround I use Python 3.7. The following instructions can be used to install Python 3.7 and to make it work with Praktomat. Warning: I wrote the instructions afterwards (I had to play around a bit), so there is a small risk that I missed a step or I misspelled a command.

### Detailed instructions
1. Install Python 3.7
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
```

2. Setup the Praktomat but use `python3.7 ...` when you create the virtualenv for the praktomat. 
Use `python3.7 -m virtualenv --system-site-packages env/` instead of `virtualenv -p python3 --system-site-packages env/`

3. Install python3.7-dev. This is needed to install mod-wsgi (through pip) later.
`sudo apt-get install python3.7-dev`

4. Create a new virtualenv that is used by apache2 later.
`python3.7 -m virtualenv --system-site-packages apache_wsgi_env`

5. Install mod-wsgi inside the virtualenv from step 4.
`source apache_wsgi_env/bin/activate`
`pip install mod-wsgi`

6. Change /etc/apache2/mods-available/wsgi.load to use the virtualenv from step 4.
`source apache_wsgi_env/bin/activate`
Execute `mod_wsgi-express module-config` and copy the output.
The output is like:
```
LoadModule wsgi_module "/srv/praktomat/apache_wsgi_env/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "/srv/praktomat/apache_wsgi_env"
```

Open  /etc/apache2/mods-available/wsgi.load (`sudo vim  /etc/apache2/mods-available/wsgi.load`) and replace the existing with the copied output. The file should look like this:
```
LoadModule wsgi_module "/srv/praktomat/apache_wsgi_env/lib/python3.7/site-packages/mod_wsgi/server/mod_wsgi-py37.cpython-37m-x86_64-linux-gnu.so"
WSGIPythonHome "/srv/praktomat/apache_wsgi_env"
# LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
```

Save the file and restart apache (`sudo service apache2 restart`). Now you can also remove the installed wsgi package (`sudo apt-get remove libapache2-mod-wsgi-py3`).

This steps worked for me and praktomat is running on Ubuntu 20.04 with Python 3.7.8.

**Comment by chris21k** [comment]
Imho using praktomat should be possible without such ugly workarounds out of the box in newer python versions and without the need of downgrading python.

**Comment by ifrh** [comment]
In addition to the bug  "Disallow fork in a subinterpreter broke subprocesses in mod_wsgi daemon mode" https://bugs.python.org/issue37951 (Python 3.8, Python 3.9) mentioned above in https://github.com/KITPraktomatTeam/Praktomat/issues/312#issue-624834177, the following bugs also seem to be of interest in this context : 

- Python 3.9 : subprocess: add user, group and extra_groups parameters : https://bugs.python.org/issue36046
- Python 3.9 : Add support for settting umask in subprocess children : https://bugs.python.org/issue38417

Quote from https://bugs.python.org/issue38417#msg354398 : 

> preexec_fn has been mentally and advisability deprecated for years. 
> I'll mark it officially with pending deprecation in 3.9 destined to be removed in 3.11.  tracking that in its own rollup issue https://bugs.python.org/issue38435

**Comment by ifrh** [comment]
Quote from  bpo-34651 "Disallow fork in a subinterpreter." https://bugs.python.org/issue34651#msg343421

> > I'd start by documenting the limitation and keeping a future feature request of "Allow subprocess to work from subinterpreters".  That is doable.  Supporting os.fork() is not.
> 
> subprocess is able to use os.posix_spawn() in Python 3.8. In that case, it's not limited by os.fork() check ;-) Windows isn't limited neither, CreateProcess() isn't limited in subinterpreters.

Quote from bpo-37951 "Disallow fork in a subinterpreter broke subprocesses in mod_wsgi daemon mode" https://bugs.python.org/issue37951#msg354130

> preexec_fn is fundamentally unsupportable.
> 
> what code is using it, there should be a way not to rely on that.

Quote from https://docs.python.org/3/library/subprocess.html

> Changed in version 3.8: The preexec_fn parameter is no longer supported in subinterpreters. The use of the parameter in a subinterpreter raises [RuntimeError](https://docs.python.domainunion.de/3/library/exceptions.html#RuntimeError). The new restriction may affect applications that are deployed in mod_wsgi, uWSGI, and other embedded environments.

**Comment by ifrh** [comment]
@ratefuchs  @hannesbraun @physikerwelt : 
To make Praktomat compatible with Python 3.8 and heigher, this code part must be change not to use `preexec_fn` .
Or what do you think?

https://github.com/KITPraktomatTeam/Praktomat/blob/aafbeb16c8200c48c0e89074bf22b162ab329d96/src/utilities/safeexec.py#L92-L115

**Comment by physikerwelt** [comment]
I don't know.

**Comment by ifrh** [comment]
mhm ... perhaps there must be a switch ... using `subprocess.Popen` with `preexec_fn` for Python versions < 3.8 and using an other way for Python versions >= 3.8. From my first quess using `os.posix_spawn` should be the way for Python versions >= 3.8

**Comment by ifrh** [comment]
I am unsure what `**other_popen_kwargs` in documentation of `subprocess.run` exactly means:
If `subprocess.run` can use `start_new_session` argument, documented for `Popen`, than there is a replacement for calling `os.setsid()` from `prepare_subprocess()`. 
Since in `prepare_subprocess()` there are calls to `resource.setrlimit` we need to handle them too, to sad, that we cannot use  `preexec_fn` parameter from `Popen` for calling `prepare_subprocess()` in Py38 and heigher from subinterpreters.

An other idea is to create a trampolin (python or C based) application, which doing all stuff from `prepare_subprocess()`:
Than in `safeexec.py`  the function `execute_arglist` could call this trampolin via `subprocess.run`, that trampolin configures resources and calls `subprocess.run` itself to start the "external command".  

Other projects which are affected by changes of `preexec_fn` had some interesting ideas to handle the situation:

- https://github.com/freeipa/freeipa/pull/3769#discussion_r332215924

- one example of a bigger trampolin is https://github.com/openstack/oslo.concurrency/blob/master/oslo_concurrency/prlimit.py

**Comment by ifrh** [comment]
Oh yes, if we choose to write the trampolin application, which is called by Praktomat code, in python,
than that trampolin should not only doing `prepare_subprocess()` stuff, but since it is a "subprocess" vom Praktomat point of view, it should close itsself, if parent process ( = Praktomat ) is gone away. 
An small implementation for that, is shown  in `ensure_dead_with_parent.py` https://gist.github.com/ambv/00641bc0fc101fc91077860649fc6017

**Comment by ifrh** [comment]
If we have a praktical idea as solution for handling the `preexec_fn`-subinterpreter-problem inside `safeexec.py`, 
perhaps it would be a good to write a unit test calling `JavaBuilder.py` using a python subinterpreter, too.

Some application issues using modwsgi and subinterpreters are listed here:
https://code.google.com/archive/p/modwsgi/wikis/ApplicationIssues.wiki#Multiple_Python_Sub_Interpreters

Since python subinterpreters cannot be created from python, the subinterpreters have to be created via C-API

1. https://docs.python.org/3/c-api/init.html#c.Py_Initialize and
2. https://docs.python.org/3/c-api/init.html#c.Py_NewInterpreter

Pythons C-API
- https://docs.python.org/3/c-api/
- https://docs.python.org/3/extending/index.html#extending-index

Quote from https://emptysqua.re/blog/python-c-extensions-and-mod-wsgi/
> Python scripts in a mod_wsgi daemon process are isolated from each other in separate Python sub interpreters, but the state of their C extensions is not isolated.

Quote from https://modpython.org/live/current/doc-html/pythonapi.html#multiple-interpreters
> [...] it is important to be aware of a feature of Python that is normally not used when using the language for writing scripts to be run from command line. (In fact, this feature is not available from within Python itself and can only be accessed through the [C language API](https://www.python.org/doc/current/api/api.html).) Python C API provides the ability to create subinterpreters.

**Comment by ifrh** [comment]
Writing a python/django unittest for Praktomat's capability to run inside Python subinterpreters (i.e. started from Apache via mod_wsgi), could be much easier, if the (provisional) module `interpreters` could be used to start a subinterpreter directly within the python/django unit test.

Quote from _PEP 554 – Multiple Interpreters in the Stdlib_ https://peps.python.org/pep-0554 :

> This proposal introduces the `stdlib` interpreters module. The module will be [provisional](https://peps.python.org/pep-0554/#provisional-status). It exposes the basic functionality of subinterpreters already provided by the C-API, along with new (basic) functionality for sharing data between interpreters.

As far as I can see, there is currently no official module `interpreters` for Python 3.9, 3.10

- https://github.com/ericsnowcurrently/multi-core-python/issues/66 
- https://github.com/ericsnowcurrently/multi-core-python/issues/76

But there exists a "backport" of PEP 554, https://github.com/aisk/backports.interpreters ,
which promiss to work with Python 3.8 ( https://github.com/aisk/backports.interpreters/blob/master/setup.py#L12 )

I had a fast look into the the implementation file : 
- https://github.com/aisk/backports.interpreters/blob/master/backports/interpreters.py

to compaire the API of  backports.interpreters with the proposed API

- https://peps.python.org/pep-0554/#interpreters-module-api
 
I think both API are matching eachother. If `backports.interpreters` implementation works, I had not tested.

**Comment by ifrh** [comment]
In https://github.com/KITPraktomatTeam/Praktomat/issues/312#issuecomment-1068501241 I wrote:
> As far as I can see, there is currently no official module `interpreters` for Python 3.9, 3.10

In _PEP 684 – A Per-Interpreter GIL_ (from 08-Mar-2022 with target Python 3.11 , https://peps.python.org/pep-0684 ) is written: 

> The fundamental problem we’re solving here is a lack of true multi-core parallelism (for Python code) in the CPython runtime. The GIL is the cause. While it usually isn’t a problem in practice, at the very least it makes Python’s multi-core story murky, which makes the GIL a consistent distraction.
> 
> Isolated interpreters are also an effective mechanism to support certain concurrency models. PEP 554 discusses this in more detail.
> [...] 
> PEP 554 is strictly about providing a minimal stdlib module to give users access to multiple interpreters from Python code. In fact, it specifically avoids proposing any changes related to the GIL. Consider, however, that users of that module would benefit from a per-interpreter GIL, which makes PEP 554 more appealing.

Perhaps these PEPs with partnership will land in the same python version ...
